name: Publish to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '56 * * * *'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-json:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.run.outputs.CHANGED }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - name: pip cache
      uses: actions/cache@v3
      env:
        cache-name: cache-pip
      with:
        path: ~/.cache/pip
        key: ${{ env.cache-name }}-${{ hashFiles('**/requirements/*') }}
        restore-keys: ${{ env.cache-name }}-

    # Cache versions.json so it doesn't update the site if there are no changes
    - name: versions.json cache
      uses: actions/cache@v3
      env:
        cache-name: cache-versions-json
      with:
        path: "data/*.json"
        key: ${{ env.cache-name }}-${{ hashFiles('**/data/*.json') }}
        restore-keys: ${{ env.cache-name }}-

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Run k3s-versions
      id: run
      run: |
        pip install -r requirements.txt
        python k3s-versions.py | tee "${GITHUB_OUTPUT}"

    - name: Upload artifacts
      if: steps.run.outputs.CHANGED == 'true'
      uses: actions/upload-artifact@v3
      with:
        path: data/
        name: k3s-versions

  # Deployment job
  build-ui:
    if: |
      needs.build-json.outputs.CHANGED == 'true' ||
      needs.build-json.changes.src == 'true'
    runs-on: ubuntu-latest
    needs: build-json
    permissions:
      pages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download json from build-json job
        uses: actions/download-artifact@v3
        with:
          name: k3s-versions
          path: data/

      - name: Deploy to GitHub Pages
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: x-access-token:${{ secrets.GITHUB_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
          working-dir: "./frontend"
